-- PlatformOps schema v1 (PostgreSQL; also runs on H2 in PostgreSQL mode for tests)

CREATE TABLE users (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email            VARCHAR(254) NOT NULL,
    full_name        VARCHAR(120) NOT NULL,
    password_hash    VARCHAR(100) NOT NULL,
    role             VARCHAR(20)  NOT NULL,
    enabled          BOOLEAN      NOT NULL DEFAULT TRUE,
    failed_attempts  INTEGER      NOT NULL DEFAULT 0,
    locked_until     TIMESTAMP WITH TIME ZONE,
    last_login_at    TIMESTAMP WITH TIME ZONE,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'DEVOPS', 'DEVELOPER', 'VIEWER'))
);

CREATE TABLE refresh_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash   VARCHAR(64)  NOT NULL,
    expires_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at   TIMESTAMP WITH TIME ZONE,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    user_agent   VARCHAR(255),
    ip_address   VARCHAR(64),
    CONSTRAINT uk_refresh_tokens_hash UNIQUE (token_hash)
);
CREATE INDEX ix_refresh_tokens_user ON refresh_tokens (user_id);

CREATE TABLE applications (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(63)  NOT NULL,
    description       VARCHAR(500) NOT NULL,
    runtime           VARCHAR(60)  NOT NULL,
    owner_team        VARCHAR(80)  NOT NULL,
    repo_url          VARCHAR(255) NOT NULL,
    status            VARCHAR(20)  NOT NULL,
    current_version   VARCHAR(64),
    last_deployed_at  TIMESTAMP WITH TIME ZONE,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_applications_name UNIQUE (name),
    CONSTRAINT ck_applications_status CHECK (status IN ('HEALTHY', 'WARNING', 'CRITICAL'))
);

CREATE TABLE environments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code              VARCHAR(20)  NOT NULL,
    display_name      VARCHAR(60)  NOT NULL,
    cluster           VARCHAR(80)  NOT NULL,
    namespace         VARCHAR(63)  NOT NULL,
    status            VARCHAR(20)  NOT NULL,
    health_score      INTEGER      NOT NULL DEFAULT 100,
    pods_running      INTEGER      NOT NULL DEFAULT 0,
    current_version   VARCHAR(64),
    last_deployed_at  TIMESTAMP WITH TIME ZONE,
    sort_order        INTEGER      NOT NULL,
    requires_approval BOOLEAN      NOT NULL DEFAULT FALSE,
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_environments_code UNIQUE (code),
    CONSTRAINT ck_environments_code CHECK (code IN ('DEV', 'STAGING', 'PRODUCTION')),
    CONSTRAINT ck_environments_status CHECK (status IN ('HEALTHY', 'DEGRADED', 'DOWN')),
    CONSTRAINT ck_environments_health CHECK (health_score BETWEEN 0 AND 100)
);

CREATE TABLE deployments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id   BIGINT       NOT NULL REFERENCES applications (id) ON DELETE CASCADE,
    environment_id   BIGINT       NOT NULL REFERENCES environments (id),
    release_version  VARCHAR(64)  NOT NULL,
    status           VARCHAR(20)  NOT NULL,
    current_stage    VARCHAR(20),
    progress         INTEGER      NOT NULL DEFAULT 0,
    triggered_by_id  BIGINT       REFERENCES users (id) ON DELETE SET NULL,
    commit_sha       VARCHAR(40),
    build_number     INTEGER,
    image_uri        VARCHAR(255),
    notes            VARCHAR(500),
    failure_reason   VARCHAR(500),
    rollback_of_id   BIGINT       REFERENCES deployments (id) ON DELETE SET NULL,
    cancel_requested BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    started_at       TIMESTAMP WITH TIME ZONE,
    finished_at      TIMESTAMP WITH TIME ZONE,
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT ck_deployments_status CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
    CONSTRAINT ck_deployments_progress CHECK (progress BETWEEN 0 AND 100)
);
CREATE INDEX ix_deployments_created ON deployments (created_at);
CREATE INDEX ix_deployments_app_env ON deployments (application_id, environment_id);
CREATE INDEX ix_deployments_status ON deployments (status);

CREATE TABLE deployment_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deployment_id  BIGINT       NOT NULL REFERENCES deployments (id) ON DELETE CASCADE,
    stage          VARCHAR(20)  NOT NULL,
    level          VARCHAR(10)  NOT NULL,
    message        VARCHAR(1000) NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_deployment_logs_deployment ON deployment_logs (deployment_id);

CREATE TABLE incidents (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(160) NOT NULL,
    description      VARCHAR(2000),
    severity         VARCHAR(10)  NOT NULL,
    status           VARCHAR(20)  NOT NULL,
    application_id   BIGINT       REFERENCES applications (id) ON DELETE SET NULL,
    environment_id   BIGINT       REFERENCES environments (id) ON DELETE SET NULL,
    deployment_id    BIGINT       REFERENCES deployments (id) ON DELETE SET NULL,
    assignee_id      BIGINT       REFERENCES users (id) ON DELETE SET NULL,
    reported_by_id   BIGINT       REFERENCES users (id) ON DELETE SET NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    acknowledged_at  TIMESTAMP WITH TIME ZONE,
    resolved_at      TIMESTAMP WITH TIME ZONE,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT ck_incidents_severity CHECK (severity IN ('SEV1', 'SEV2', 'SEV3', 'SEV4')),
    CONSTRAINT ck_incidents_status CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED'))
);
CREATE INDEX ix_incidents_status ON incidents (status);

CREATE TABLE audit_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id     BIGINT,
    actor_email  VARCHAR(254),
    action       VARCHAR(60)  NOT NULL,
    entity_type  VARCHAR(40)  NOT NULL,
    entity_id    VARCHAR(64),
    details      VARCHAR(2000),
    ip_address   VARCHAR(64),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_audit_events_created ON audit_events (created_at);
CREATE INDEX ix_audit_events_action ON audit_events (action);
