{
 "title": "PlatformOps API",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests / second",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{application=\"platformops-api\", uri!~\"/actuator.*\"}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "p95 latency (s)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_server_requests_seconds_bucket{application=\"platformops-api\"}[5m])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "5xx in last 5m",
   "type": "stat",
   "gridPos": { "x": 0, "y": 8, "w": 6, "h": 6 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"platformops-api\", status=~\"5..\"}[5m])) or vector(0)"
    }
   ]
  },
  {
   "title": "JVM heap used",
   "type": "stat",
   "gridPos": { "x": 6, "y": 8, "w": 6, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"platformops-api\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "DB connections active",
   "type": "stat",
   "gridPos": { "x": 12, "y": 8, "w": 6, "h": 6 },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_active{application=\"platformops-api\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "x": 18, "y": 8, "w": 6, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(process_uptime_seconds{application=\"platformops-api\"})"
    }
   ]
  }
 ]
}